### ISSUE TITLE
How to read the training.msgpack file after training?

### ISSUE THREAD

**Issue by ghost** [ZHKKKe/DualStudent#2]

**Comment by ZHKKKe** [comment]
Hi! Thanks for your attention!

This msgpack function is adapted from _Mean Teacher_. 
To read the ''training.msgpack'' file, you first need to `import pandas`. Then you can read the contents by using `pandas.read_msgpack('your_storage_path/training.msgpack')`. 

I suggest that you can also try to use `logging.FileHandler` to save the training log. To achieve this, you can add following code after the Line-73 of `./scripts/ds_cifar10_1000l_cnn13.py` (or the same place in other scripts):
```
fh = logging.FileHandler('{0}/log.txt'.format(context.result_dir))
fh.setLevel(logging.INFO)
LOG.addHandler(fh)
```

I have updated the corresponding code to the repository. Please pull the latest version and try it.
