### ISSUE TITLE
Do l_input and r_input belong to the same image but augmented differently?

### ISSUE THREAD

**Issue by dbjhbyun** [ZHKKKe/DualStudent#3]
Hi I was looking through the code but I couldn't figure out whether l_input and r_input belong to the same image but augmented differently (different noise applied). Can you clarify? Thanks in advance!

**Comment by dbjhbyun** [comment]
I know that the indices come from TwoStreamBatch (batch sampling module). It seemed to me that it returns different indices for its output[0] and output[1] so I suppose l_input and r_output belong to completely different images?

**Comment by ZHKKKe** [comment]
Hi! Thanks for your attention!

In our code, `l_input` and `r_input` belong to the same image but augmented differently.

As shown in `./third_party/mean_teacher/data.py [Line-137]`, `TwoStreamBatchSampler` fetches the indices of both unlabeled images (`primary_indices`) and labeled images (`secondary_indices`) and combines them as the indices of a minibatch for returning. Therefore, the indices returned by `TwoStreamBatchSampler` represent different images. Meanwhile, the first several indices belong to the unlabeled image while the others belong to the labeled image. The number of the labeled image is controlled by `labeled_batch_size` (or `base_labeled_batch_size`) in the script. In Dual Student, all images corresponding to these indices will be input to two students splitly after different augmentation.

In `./dual_student.py [Line-78]`, we create an instance of `torch.utils.data.DataLoader` and read a minibatch by using `TwoStreamBatchSampler`. Here, the `dataset` is defined in `./dual_student.py [Line-35]`, which takes a `train_transformation` as the parameter. You can find the definition of `transformation`, i.e., augmentation, for each dataset in `./src/datasets.py`. For example, the `train_transformation` of CIFAR-10 is defined in`./src/datasets.py [Line-15]`. Here you can see a class named ` TransformNTimes`. It is defined in `./third_party/mean_teacher/data.py [Line-82]`. This class indicates the number of augmentation to be performed for each image in the minibatch. The augmented samples will be combined as a list. In Dual Student, we set `n=2` to create `l_input` and `r_input`. For Multiple Student, we set `n=[the number of students]`. 

That is how our code gets `l_input` and `r_input` (for Dual Student) during training.

**Comment by dbjhbyun** [comment]
Thank you for such a detailed answer! That clarified everything! Awesome work by the way!

**Comment by jhb115** [comment]
Hi, I am curious from which part of your code let you get (l_input, r_input) i.e. a tuple of two batches.
The TwoStreamBatchSampler seem to return a single batch (not as a tuple of two batches). I just couldn't figure out from which part of the code let the DataLoader return a tuple of (l_input, r_input)
Looking forward to your reply. Thanks in advance!

**Comment by ZHKKKe** [comment]
Hi, @jhb115 . Thanks for your attention!

In brief:
(1) I define a class that named `TransformNTimes` in `./third_party/mean_teacher/data.py [Line-82]`. This class indicates the number of augmentation to be performed for each image in the minibatch.

(2)  In `./src/datasets.py`, I define the `transformation` of each dataset. The `transformation` contains the function `TransformNTimes`, which randomly transforms each image in the minibatch for `n` times.

(3) We take the `transformation` defined in (2) as the input of the PyTorch dataset (as shown in `./dual_student.py [Line-35]`). Therefore, each image in the minibatch will be transformed for `n` times and combined as a tuple for returning. In Dual Student, we set `n` to 2, which returns a tuple of `(l_input, r_input)`.

Please refer to the second paragraph of my above answer for more details.
