### ISSUE TITLE
Question about the Dual Student model

### ISSUE THREAD

**Issue by MLRadfys** [ZHKKKe/DualStudent#8]
Hi and thanks for your interesting work!

I went through you code and Iam just wondering why the CNN13 model has two outputs?

Thanks in advance,

best regards,

M

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
The two outputs (one for supervised loss and one for consistency loss) trick is proposed by the Mean Teacher paper. Adding an additional consistency constraint between the two outputs helps improve the performance.

**Comment by MLRadfys** [comment]
Hi and thanks for the quick reply! 
I found the relevant section in the Mean Teacher paper, thanks :-)

Best regards,

M
